#!/bin/bash
#
#   cloudforms_essentialsrc
#
#   Author: Kevin Morey <kevin@redhat.com>
#
#   Description: This bash script initializes some useful aliases that assist 
#                CloudForms administrators
#
#   Installation: Place this file in root's home direcotry and then source this 
#                 file. e.g. # source ~/cloudforms_essentialsrc
#
#   -------------------------------------------------------------------------------
#    Copyright 2017 Kevin Morey <kevin@redhat.com>
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
# -------------------------------------------------------------------------------

# Directory settings
VMDB_PATH='/var/www/miq/vmdb'

# Logging aliases
alias log='cd $VMDB_PATH/log'
alias tailauto='less +F $VMDB_PATH/log/automation.log'
alias tailevm='less +F $VMDB_PATH/log/evm.log'
alias tailprod='less +F $VMDB_PATH/log/production.log'
alias tailpolicy='less +F $VMDB_PATH/log/policy.log'

# Clean logging aliases
alias clean_evm="echo Cleaned: `date` > $VMDB_PATH/log/evm.log"
alias clean_auto="echo Cleaned: `date` > $VMDB_PATH/log/automation.log"
alias clean_prod="echo Cleaned: `date` > $VMDB_PATH/log/production.log"
alias clean="clean_evm;clean_auto;clean_prod"

# Rails Console
alias railsc="vmdb;echo '\$evm = MiqAeMethodService::MiqAeService.new(MiqAeEngine::MiqAeWorkspaceRuntime.new)'; rails c"

# kill provision job
function kill_prov {
  vmdb
  rails r tools/kill_provision.rb $1
  cd - > /dev/null 2>&1
}

# Ignore duplicate history commands
export HISTCONTROL=ignoredups
